# Generated by Django 4.1.2 on 2022-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ekonomi', 'Ekonomi'), ('sosial-dan-budaya', 'Sosial Budaya'), ('pendidikan', 'Pendidikan'), ('pemerintahan', 'Pemerintah'), ('politik', 'Politik'), ('lainnya', 'Lainnya')], default='lainnya', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
