# Generated by Django 4.1.2 on 2022-11-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='penulis',
            field=models.CharField(default='admin', max_length=255),
        ),
    ]
