# Generated by Django 4.1.2 on 2022-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indonesia', '0005_rename_penulis_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/indonesia/'),
        ),
    ]
