# Generated by Django 4.1.2 on 2022-11-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendidikan', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
